/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "platform_Types.h"

#define RCC_BASE 	0x40021000
#define GPIOA_BASE 	0x40010800

#define RCC_APB2ENR *(volatile uint32 *)(RCC_BASE + 0x18)
#define GPIOA_CRH   *(volatile uint32 *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR	*(volatile uint32 *)(GPIOA_BASE + 0x0C)

#define RCC_IOPAEN	(1UL<<2)
#define GPIOA13		(1UL<<13)

unsigned char g_bss;
unsigned char g_data;
unsigned char const g_const = 1;

int main(void)
{
	int i;
	RCC_APB2ENR |= RCC_IOPAEN;
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1)
	{
		GPIOA_ODR ^= GPIOA13;
		for(i = 0; i < 100000; i++);
	}
}
